### ISSUE TITLE
get videos list by user not working with cursor greater than 0

### ISSUE THREAD

**Issue by truongbo17** [pablouser1/TikScraperPHP#10]
code example

```
$api = new \TikScraper\Api([
    'signer' => [
        'method' => 'remote',
        'url' => 'http://localhost:8080/signature'
    ]
]);
$item = $api->user('ibaillanos');
$full = $item->feed(10)->getFull();
echo $full->toJson();
```

and this return null

**Comment by truongbo17** [comment]
Update : 

`$full = $item->feed(10)->getFull();`

**Comment by DmytroHudenko** [comment]
I have the same issue

**Comment by farzad119** [comment]
Same

**Comment by truongbo17** [comment]
same cc

**Comment by MohaMBS** [comment]
Someone solved it? Because it seems to be a problem with the cursor, they have changed the way it works
In addition, several public instances of ProxiTok that work correctly with the cursor, others do not and have the latest public version of the Scraper

**Comment by SuperSonicHub1** [comment]
Connecting this to https://github.com/pablouser1/ProxiTok/issues/94

**Comment by truongbo17** [comment]
> Connecting this to [pablouser1/ProxiTok#94](https://github.com/pablouser1/ProxiTok/issues/94)

follow here.
