### ISSUE TITLE
Get UserFeed with cursor Not working

### ISSUE THREAD

**Issue by Spawnrad** [pablouser1/TikScraperPHP#13]
Hi,

I tried to get user feed with a cursor and it doesn't work. 
It looks like its the API calls that doesn't work maybe something change but i can't figure out what it is.

sendHTML => working with cursor=0
sendAPI  => not working with cursor=0 or anything else

If someone know how to solve that issue.

**Comment by Spawnrad** [comment]
Its working now 
Have changed useragent

**Comment by EazyFTW** [comment]
Sorry to bump (I couldn't find another way to contact you), but is this still working for you? I checked out your fork, and this still seems to be an issue with it. I'm getting curl errors for some reason (10).

**Comment by Spawnrad** [comment]
Hi @EazyFTW 

The user agent must be the same on Remote signing. Is this ok?

**Comment by EazyFTW** [comment]
> Hi @EazyFTW
> 
> The user agent must be the same on Remote signing. Is this ok?

It doesn't seem to work. I keep getting the same curl error.
